version: "3.9"
services:
  web:
    build: .
    container_name: django_web
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - .:/usr/src/app
      - db_data:/usr/src/app/data 
    networks:
      - crai_net
volumes:
  db_data:
networks:
  crai_net:
    external: true